spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBXfCKJZ2aNC07eE8Kt2o85bvBXfcjTnvWrTQ7TOaorws2S3reXs+Y+NVMFaw+KWPRwY9wgirn13c9h8qpv79w/YooWmp6oZVxRr104ylH0RXxZD2UmVU+J+7BIODUPlexdrOeryAY/X4cs7VZ6jzzXp4wB5fIrH3q1o8nTVRLHNku1kBVcMVZqXFdU7TurjfPahMyVk8NFSjV5MoCp6ESy0LAtuD5SOVUhJMJfrrwoF2SNf96r2hd6ZaK3OOSPF4Eekz8Xud8Uk4NPaqifb1Kmw5QcJmIefBuvJDKj8D+cJDxPPbGv+FQ4BSQYgW+28MI1mq8mdSfNJEA+zt1uOIErsDIulwaU/vVOIjn4/KAtybSUdK5/dvMvrfSUuqAfNto='

token:
  expiration_time: 86400000
  secret: new_user_token_7

gateway:
  ip: 172.18.0.5
